// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class CategoryAttribute
{
    public int CategoryId { get; set; }

    public int AttributeId { get; set; }

    public bool IsFilterable { get; set; }

    public virtual Attribute Attribute { get; set; }

    public virtual Category Category { get; set; }
}