// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class CategorySpecOption
{
    public int Id { get; set; }

    public int CategorySpecId { get; set; }

    public string OptionName { get; set; }

    public int SortOrder { get; set; }
}