// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ISpanShop.Models.EfModels;

public partial class ISpanShopDBContext : DbContext
{
    public ISpanShopDBContext(DbContextOptions<ISpanShopDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<AdminLevel> AdminLevels { get; set; }

    public virtual DbSet<BlacklistRecord> BlacklistRecords { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<CategorySpec> CategorySpecs { get; set; }

    public virtual DbSet<CategorySpecMapping> CategorySpecMappings { get; set; }

    public virtual DbSet<CategorySpecOption> CategorySpecOptions { get; set; }

    public virtual DbSet<ChatMessage> ChatMessages { get; set; }

    public virtual DbSet<LoginHistory> LoginHistories { get; set; }

    public virtual DbSet<MemberProfile> MemberProfiles { get; set; }

    public virtual DbSet<MembershipLevel> MembershipLevels { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<OrderReview> OrderReviews { get; set; }

    public virtual DbSet<PaymentLog> PaymentLogs { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<PointHistory> PointHistories { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductVariant> ProductVariants { get; set; }

    public virtual DbSet<ReturnRequest> ReturnRequests { get; set; }

    public virtual DbSet<ReturnRequestImage> ReturnRequestImages { get; set; }

    public virtual DbSet<ReviewImage> ReviewImages { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SensitiveWord> SensitiveWords { get; set; }

    public virtual DbSet<SensitiveWordCategory> SensitiveWordCategories { get; set; }

    public virtual DbSet<Store> Stores { get; set; }

    public virtual DbSet<SupportTicket> SupportTickets { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Address>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Addresse__3214EC077BFAE9DB");

            entity.Property(e => e.City).HasMaxLength(20);
            entity.Property(e => e.RecipientName).HasMaxLength(50);
            entity.Property(e => e.RecipientPhone)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Region).HasMaxLength(20);
            entity.Property(e => e.Street).HasMaxLength(200);
        });

        modelBuilder.Entity<AdminLevel>(entity =>
        {
            entity.HasIndex(e => e.LevelName, "UQ_AdminLevels_Name").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.LevelName)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasMany(d => d.Permissions).WithMany(p => p.AdminLevels)
                .UsingEntity<Dictionary<string, object>>(
                    "AdminLevelPermission",
                    r => r.HasOne<Permission>().WithMany()
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("FK_ALP_Permissions"),
                    l => l.HasOne<AdminLevel>().WithMany()
                        .HasForeignKey("AdminLevelId")
                        .HasConstraintName("FK_ALP_AdminLevels"),
                    j =>
                    {
                        j.HasKey("AdminLevelId", "PermissionId");
                        j.ToTable("AdminLevelPermissions");
                    });
        });

        modelBuilder.Entity<BlacklistRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Blacklis__3214EC072EFCA42D");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Reason).HasMaxLength(200);
            entity.Property(e => e.UnblockAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Brand>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Brands__3214EC07EA0D44BC");

            entity.Property(e => e.LogoUrl).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Carts__3214EC0774F01B24");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CartItem__3214EC0789C6D2D8");

            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC0722CCFD17");

            entity.Property(e => e.Icon).HasMaxLength(255);
            entity.Property(e => e.IconUrl).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NameEn).HasMaxLength(100);
        });

        modelBuilder.Entity<CategorySpec>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Category__3214EC07BF5DA117");

            entity.Property(e => e.InputType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<CategorySpecMapping>(entity =>
        {
            entity.HasKey(e => new { e.CategoryId, e.CategorySpecId }).HasName("PK__Category__FF254218CCE4A84D");
        });

        modelBuilder.Entity<CategorySpecOption>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Category__3214EC07B444EF33");

            entity.Property(e => e.OptionName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ChatMessage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ChatMess__3214EC0789CD0610");

            entity.Property(e => e.SentAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<LoginHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LoginHis__3214EC07E005BE53");

            entity.ToTable("LoginHistory");

            entity.Property(e => e.Ipaddress)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("IPAddress");
            entity.Property(e => e.LoginTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<MemberProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MemberPr__3214EC07DB9C3F16");

            entity.Property(e => e.FullName).HasMaxLength(50);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TotalSpending).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<MembershipLevel>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Membersh__3214EC07557F1C16");

            entity.Property(e => e.DiscountRate).HasColumnType("decimal(3, 2)");
            entity.Property(e => e.LevelName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.MinSpending).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Orders__3214EC075649106B");

            entity.Property(e => e.CompletedAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.FinalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.OrderNumber)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.RecipientAddress).HasMaxLength(300);
            entity.Property(e => e.RecipientName).HasMaxLength(50);
            entity.Property(e => e.RecipientPhone)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ShippingFee).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderDet__3214EC071E161B81");

            entity.Property(e => e.CoverImage).HasMaxLength(500);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ProductName).HasMaxLength(200);
            entity.Property(e => e.SkuCode).HasMaxLength(100);
            entity.Property(e => e.VariantName).HasMaxLength(100);
        });

        modelBuilder.Entity<OrderReview>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderRev__3214EC072E5A8084");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<PaymentLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentL__3214EC073AC97B24");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.MerchantTradeNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentType)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RtnMsg).HasMaxLength(200);
            entity.Property(e => e.TradeAmt).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TradeNo)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasIndex(e => e.PermissionKey, "UQ_Permissions_Key").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PermissionKey)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PointHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PointHis__3214EC072B27610F");

            entity.ToTable("PointHistory");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.OrderNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Products__3214EC07E3897620");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.MaxPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.RejectDate).HasColumnType("datetime");
            entity.Property(e => e.ReviewDate).HasColumnType("datetime");
            entity.Property(e => e.ReviewedBy).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.VideoUrl).HasMaxLength(500);
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductI__3214EC078CA039AB");

            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<ProductVariant>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductV__3214EC077CEFCBEC");

            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SkuCode).HasMaxLength(100);
            entity.Property(e => e.VariantName).HasMaxLength(100);
        });

        modelBuilder.Entity<ReturnRequest>(entity =>
        {
            entity.Property(e => e.AdminRemark).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ReasonCategory).HasMaxLength(50);
            entity.Property(e => e.RefundAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithMany(p => p.ReturnRequests)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReturnRequests_Orders");
        });

        modelBuilder.Entity<ReturnRequestImage>(entity =>
        {
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.ReturnRequest).WithMany(p => p.ReturnRequestImages)
                .HasForeignKey(d => d.ReturnRequestId)
                .HasConstraintName("FK_ReturnRequestImages_ReturnRequests");
        });

        modelBuilder.Entity<ReviewImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReviewIm__3214EC07E95D51EE");

            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC07F438C23C");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<SensitiveWord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sensitiv__3214EC0729707063");

            entity.Property(e => e.Category).HasMaxLength(50);
            entity.Property(e => e.CreatedTime).HasColumnType("datetime");
            entity.Property(e => e.Word)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.CategoryNavigation).WithMany(p => p.SensitiveWords)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_SensitiveWords_Categories");
        });

        modelBuilder.Entity<SensitiveWordCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sensitiv__3214EC076EC90893");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Store>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Stores__3214EC07ADB3100A");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.StoreName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SupportTicket>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SupportT__3214EC0758065689");

            entity.Property(e => e.AttachmentUrl).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ResolvedAt).HasColumnType("datetime");
            entity.Property(e => e.Subject).HasMaxLength(100);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC07CA8F6B0A");

            entity.Property(e => e.Account)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ConfirmCode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsFirstLogin).HasDefaultValue(true);
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Provider)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ProviderId)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.AdminLevel).WithMany(p => p.Users)
                .HasForeignKey(d => d.AdminLevelId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Users_AdminLevels");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}