// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class SensitiveWordCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<SensitiveWord> SensitiveWords { get; set; } = new List<SensitiveWord>();
}