// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ISpanShop.Models.EfModels;

public partial class SensitiveWord
{
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Word { get; set; }

    // 1. 新增這個：記錄分類的 ID
    public int CategoryId { get; set; } 

    // 2. 新增這個：對應到分類實體的導覽屬性
    public virtual SensitiveWordCategory Category { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedTime { get; set; }
}