// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ISpanShop.Models.EfModels;

public partial class User
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Provider { get; set; }

    public string ProviderId { get; set; }

    public bool? IsConfirmed { get; set; }

    public string ConfirmCode { get; set; }

    public bool? IsBlacklisted { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? AdminLevelId { get; set; }

    public bool IsFirstLogin { get; set; }

    public virtual AdminLevel AdminLevel { get; set; }
}